url: https:/kyte.travel
sass:
    sass_dir: _scss
    style: compressed
    
notice:
  - title: "태풍 관련 항공편 운항 안내"
    url: /notice/admin
    
promotion:
  - category: "진행중인 프로모션"
    items:
    - title: "프로모션 이름"
      url: /promotion/account
  - category: "지난 프로모션"
    items:
    - title: "가을맞이 인기도시 항공권 특가"
      url: /promotion/account
    - title: "하와이안 항공 최대 5% 할인"
      url: /promotion/account
    - title: "북미/유럽/동남아 인기도시 최대 5% 할인"
      url: /promotion/account
    - title: "대한항공/아시아나항공 전 노선 추가 5천원 할인"
      url: /promotion/account
    - title: "북미/유럽/동남아 인기도시 추가 3천원 할인"
      url: /promotion/account
    - title: "아시아나항공 유럽 단독 특가"
      url: /promotion/account
    - title: "대한항공 미주 인기도시 스페셜 할인"
      url: /promotion/account
    - title: "아시아나항공 일본 얼리버드 특가"
      url: /promotion/account
    - title: "하와이안항공 항공권 특가"
      url: /promotion/account
    - title: "아시아나항공 15개 도시 항공권 특가"
      url: /promotion/account
    - title: "유럽 10개 도시, 10개 항공사 항공권 특가 할인"
      url: /promotion/account
    - title: "미주/캐나다 15개 도시 최대 7% 할인"
      url: /promotion/account
    
faq:
  - category: "시작하기"
    items:
    - title: "카이트는 어떤 서비스 인가요?"
      url: /faq/about-kyte
    - title: "구매한 항공권은 어디서 확인할 수 있나요?"
      url: /faq/purchased
    - title: "편도 항공권 구매가 가능한가요?"
      url: /faq/oneway
    - title: "다구간 검색이 가능한가요?"
      url: /faq/multicity
    - title: "고객센터 전화 연결이 가능한가요?"
      url: /faq/call
  - category: "여권"
    items:
    - title: "여권 발급예정인 경우, 어떻게 결제 하나요?"
      url: /faq/passport-scheduled
    - title: "여권의 유효기간은 얼마나 남아 있어야 하나요?"
      url: /faq/passport-expired
    - title: "예약 시 영문이름이 여권상 정보와 다르면 어떻게 되나요?"
      url: /faq/passport-name
    - title: "여권과 항공권의 영문 띄어쓰기가 다른 경우에도 똑같이 수정해야 하나요?"
      url: /faq/passport-name-blank
    - title: "여권정보는 어디서 수정하나요?"
      url: /faq/change-passport
  - category: "예약/결제"
    items:
    - title: "'결제요청'은 어떤 상태인가요?"
      url: /faq/request-purchase
    - title: "미확정 요금으로 예약했는데 결제할 수 있나요?"
      url: /faq/unconfirmed
    - title: "카드 정보를 정확하게 입력했는데, 결제 진행이 안되는 경우도 있나요?"
      url: /faq/card
    - title: "현금으로 항공권 결제가 가능한가요?"
      url: /faq/cash
    - title: "결제 시 무이자 할부가 가능한가요?"
      url: /faq/interest-free-installment-plan
    - title: "중복(이중)으로 예약하면 어떻게 되나요?"
      url: /faq/duplication
    - title: "소아 및 유아 예약은 어떻게 해야하나요?"
      url: /faq/child
    - title: "미국행 항공권 예약 시 체류지 정보를 꼭 입력해야 하나요?"
      url: /faq/stay
  - category: "발권/항공권"
    items:
    - title: "항공권 유효기간은 무엇인가요?"
      url: /faq/ticket-expired
    - title: "항공사 예약 번호는 어디에서 확인하나요?"
      url: /faq/ticket-number
    - title: "전자 항공권(e-Ticket)은 어디에서 확인하나요?"
      url: /faq/e-ticket
    - title: "항공편의 스케줄이 변경되는 경우, 어떻게 알 수 있나요?"
      url: /faq/schedule-changed
    - title: "미리 좌석을 지정할 수 있나요?"
      url: /faq/seat
  - category: "마일리지"
    items:
    - title: "마일리지를 적립하려면 어떻게 해야하나요?"
      url: /faq/mileage
    - title: "마일리지가 적립되는 기준은 어떻게 되나요?"
      url: /faq/mileage-rule
    - title: "항공사 마일리지로 항공권 발권이 가능한가요?"
      url: /faq/mileage-use
    - title: "마일리지 적립이 안되었는데 어떻게 하나요?"
      url: /faq/mileage-error
  - category: "환불/변경/취소"
    items:
    - title: "항공권 환불 및 취소는 어떻게 하나요?"
      url: /faq/refund-and-cancel
    - title: "항공권 결제완료 후 변경이 가능한가요?"
      url: /faq/change-schedule
    - title: "여행 중 귀국편 변경은 어떻게 하나요?"
      url: /faq/change-schedule-return
    - title: "항공권 유효기간 연장은 어떻게 하나요?"
      url: /faq/change-expiration
    - title: "결제 후 결제수단 변경이 가능한가요?"
      url: /faq/change-purchase
    - title: "환불/취소 시 수수료는 얼마인가요?"
      url: /faq/refund-and-cancel-fee
  - category: "수하물/기내서비스"
    items:
    - title: "수하물 기준이 어떻게 되나요?"
      url: /faq/baggage
    - title: "수하물을 분실할 경우 어떻게 해야하나요?"
      url: /faq/baggage-lost
    - title: "소아 및 유아의 기내식 서비스 신청이 가능한가요?"
      url: /faq/child-meal
    - title: "유아와 함께 탑승 시 기내의 아기 바구니를 사용할 수 있나요?"
      url: /faq/baby-basket
    - title: "임산부도 탑승이 가능한가요?"
      url: /faq/pregnant
    - title: "애완동물을 데리고 탑승할 수 있나요?"
      url: /faq/pet
  - category: "비자"
    items:
    - title: "비자 대행업무가 가능한가요?"
      url: /faq/visa
    - title: "미국 비자면제프로그램(VWP)이란 무엇인가요?"
      url: /faq/visa-vwp
    - title: "호주 전자비자 발급 서비스(ETAS) 대행 업무가 가능한가요?"
      url: /faq/visa-etas
    - title: "캐나다 입국 시 비자가 필요한가요?"
      url: /faq/visa-canada
    - title: "중국을 환승하는 경우에도 비자가 필요한가요?"
      url: /faq/visa-china
    - title: "인도 입국 시 비자가 필요한가요?"
      url: /faq/visa-india
    - title: "베트남, 캄보디아, 라오스 입국 시 비자가 필요한가요?"
      url: /faq/visa-east-asis
  - category: "기타"
    items:
    - title: "탑승수속을 위해 항공편 출발 몇시간 전에 공항에 가야하나요?"
      url: /faq/boarding-time
    - title: "세금/유류할증료란 무엇인가요?"
      url: /faq/tax
    - title: "공동운항(코드쉐어)은 무엇인가요?"
      url: /faq/code-share
    - title: "스탑오버(Stop over)란 무엇인가요?"
      url: /faq/stop-over
    - title: "노쇼(No-Show)는 무엇인가요?"
      url: /faq/no-show
    - title: "소아 및 유아 요금은 어떻게 책정 되나요?"
      url: /faq/child-pricing
    - title: "어린이 혼자 비행기 탑승이 가능한가요?"
      url: /faq/child-only
    - title: "Cabotage(자국 내 항공운송권리)란 무엇인가요?"
      url: /faq/cabotage
    - title: "출력한 항공권이 있어야만 면세점을 이용할 수 있나요?"
      url: /faq/printed-ticket
      
policy:
    - title: "서비스 이용약관"
      url: /policy/terms
    - title: "개인정보 처리방침"
      url: /policy/privacy
    - title: "국외여행 이용약관"
      url: /policy/outbound-travel-policy
