title: kyte-service introduction
description: 카이트 서비스소개 페이지
# url: "https://www.playwings.co.kr"
# cloudinary: https://res.cloudinary.com/kyte/image/upload/q_auto,f_auto
sass:
  sass_dir: _scss
  style: compressed
include:
  - .well-known
exclude:
  - deploy.sh